//user types
export const SIGNING_UP = "SIGNING_UP";
export const SIGNING_UP_SOCIAL_MEDIA = "SIGNING_UP_SOCIAL_MEDIA";
export const SIGN_UP_COMPLETE = "SIGN_UP_COMPLETE";
export const SIGNING_IN = "SIGNING_IN";
export const SIGN_IN_COMPLETE = "SIGN_IN_COMPLETE";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const FETCHING_USER = "FETCHING_USER";
export const STOP_FETCHING_USER = "STOP_FETCHING_USER";
export const SET_USER = "SET_USER";

//locations types
export const GET_ALL_LOCATIONS = "GET_ALL_LOCATIONS";
export const GET_LOCATION = "GET_LOCATION";
export const CREATE_NEW_LOCATION = "CREATE_NEW_LOCATION";
export const CREATING_LOCATION = "CREATING_LOCATION";
export const JOINING_CLEAN_SITE = "JOINING_CLEAN_SITE";
export const JOINED_CLEAN_SITE = "JOINED_CLEAN_SITE";
export const CREATE_LOCATION_COMPLETE = "CREATE_LOCATION_COMPLETE";
export const GETTING_CREATED_LOCATIONS = "GETTING_CREATED_LOCATIONS";
export const GOT_CREATED_LOCATIONS = "GOT_CREATED_LOCATIONS";
export const GETTING_REGISTERED_LOCATIONS = "GETTING_REGISTERED_LOCATIONS";
export const GOT_REGISTERED_LOCATIONS = "GOT_REGISTERED_LOCATIONS";
export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";

//UI types
export const RESET_UI_STATE = "RESET_UI_STATE";
export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//Snackbars
export const OPEN_AUTHENTICATION_SNACKBAR = "OPEN_AUTHENTICATION_SNACKBAR";
export const CLOSE_AUTHENTICATION_SNACKBAR = "CLOSE_AUTHENTICATION_SNACKBAR";
export const OPEN_SIGN_OUT_SNACKBAR = "OPEN_SIGN_OUT_SNACKBAR";
export const CLOSE_SIGN_OUT_SNACKBAR = "OPEN_SIGN_OUT_SNACKBAR";

//form types
export const OPEN_JOIN_CLEAN_UP_FORM = "OPEN_JOIN_CLEAN_UP_FORM";
export const CLOSE_JOIN_CLEAN_UP_FORM = "CLOSE_JOIN_CLEAN_UP_FORM";

export const LOADING_FORM = "LOADING_FORM";
export const STOP_LOADING_FORM = "STOP_LOADING_FORM";

export const DEFAULT_URL = "https://asia-northeast1-rmit-cloud-a2-c8905.cloudfunctions.net/api";
