//user types
export const SIGNING_UP = "SIGNING_UP";
export const SIGNING_UP_SOCIAL_MEDIA = "SIGNING_UP_SOCIAL_MEDIA";
export const SIGN_UP_COMPLETE = "SIGN_UP_COMPLETE";
export const SIGNING_IN = "SIGNING_IN";
export const SIGN_IN_COMPLETE = "SIGN_IN_COMPLETE";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const FETCHING_USER = "FETCHING_USER";
export const STOP_FETCHING_USER = "STOP_FETCHING_USER";
export const SET_USER = "SET_USER";

//locations types
export const GET_ALL_LOCATIONS = "GET_ALL_LOCATIONS";
export const GET_LOCATION = "GET_LOCATION";
export const CREATE_NEW_LOCATION = "CREATE_NEW_LOCATION";
export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";

//UI types
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_ERRORS = "SET_ERRORS";
export const OPEN_AUTHENTICATION_SNACKBAR = "OPEN_AUTHENTICATION_SNACKBAR";
export const CLOSE_AUTHENTICATION_SNACKBAR = "CLOSE_AUTHENTICATION_SNACKBAR";

//form types
export const OPEN_JOIN_CLEAN_UP_FORM = "OPEN_JOIN_CLEAN_UP_FORM";
export const CLOSE_JOIN_CLEAN_UP_FORM = "CLOSE_JOIN_CLEAN_UP_FORM";
export const LOADING_FORM = "LOADING_FORM";
export const STOP_LOADING_FORM = "STOP_LOADING_FORM";
export const OPEN_CLEAN_UP_MODAL = "OPEN_CLEAN_UP_MODAL";
export const CLOSE_CLEAN_UP_MODAL = "CLOSE_CLEAN_UP_MODAL";


export const DEFAULT_URL = "https://asia-northeast1-rmit-cloud-a2-c8905.cloudfunctions.net/api";
