//user types
export const SIGNING_UP = "SIGNING_UP";
export const SIGNING_UP_SOCIAL_MEDIA = "SIGNING_UP_SOCIAL_MEDIA";
export const SIGN_UP_COMPLETE = "SIGN_UP_COMPLETE";
export const SIGNING_IN = "SIGNING_IN";
export const SIGN_IN_COMPLETE = "SIGN_IN_COMPLETE";
export const FETCHING_USER = "FETCHING_USER";
export const GOT_USER = "GOT_USER";
export const UPDATING_USER = "UPDATING_USER";
export const DONE_UPDATE_USER = "DONE_UPDATE_USER";
export const UPLOAD_PROFILE_IMAGE = "UPLOAD_PROFILE_IMAGE";

//locations types
export const GET_ALL_LOCATIONS = "GET_ALL_LOCATIONS";
export const GET_LOCATION = "GET_LOCATION";
export const CREATE_NEW_LOCATION = "CREATE_NEW_LOCATION";
export const CREATING_LOCATION = "CREATING_LOCATION";
export const JOINING_CLEAN_SITE = "JOINING_CLEAN_SITE";
export const JOINED_CLEAN_SITE = "JOINED_CLEAN_SITE";
export const DELETING_LOCATION = "DELETING_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const DELETE_LOCATION_COMPLETE = "DELETE_LOCATION_COMPLETE";
export const ALREADY_JOINED_CLEAN_SITE = "ALREADY_JOINED_CLEAN_SITE";
export const CREATE_LOCATION_COMPLETE = "CREATE_LOCATION_COMPLETE";
export const GETTING_CREATED_LOCATIONS = "GETTING_CREATED_LOCATIONS";
export const GOT_CREATED_LOCATIONS = "GOT_CREATED_LOCATIONS";
export const GETTING_REGISTERED_LOCATIONS = "GETTING_REGISTERED_LOCATIONS";
export const GOT_REGISTERED_LOCATIONS = "GOT_REGISTERED_LOCATIONS";
export const UPDATING_LOCATION = "UPDATING_LOCATION";
export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const UPDATE_LOCATION_COMPLETE = "UPDATE_LOCATION_COMPLETE";
export const UPLOADING_LOCATION_LOGO = "UPLOADING_LOCATION_LOGO";
export const DONE_UPLOAD_LOCATION_LOGO = "DONE_UPLOAD_LOCATION_LOGO";
export const LOCATION_DOES_NOT_EXIST = "LOCATION_DOES_NOT_EXIST";

//location filter types
export const FILTER_LOCATIONS_BY_KEYWORD = "FILTER_LOCATIONS_BY_KEYWORD";
export const RESET_FILTERS = "RESET_FILTERS";
export const FILTER_BY_START_DATE = "FILTER_BY_START_DATE";
export const FILTER_BY_START_DATE_WITH_CITY = "FILTER_BY_START_DATE_WITH_CITY";
export const FILTER_BY_START_DATE_WITH_CITY_AND_DISTRICT = "FILTER_BY_START_DATE_WITH_CITY_AND_DISTRICT";
export const FILTER_BY_CITY = "FILTER_BY_CITY";
export const FILTER_BY_CITY_WITH_START_DATE = "FILTER_BY_CITY_WITH_START_DATE";
export const FILTER_BY_DISTRICT = "FILTER_BY_DISTRICT";
export const FILTER_BY_DISTRICT_WITH_CITY = "FILTER_BY_DISTRICT";

//UI types
export const RESET_UI_STATE = "RESET_UI_STATE";
export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const ENLARGE_MARKER = "ENLARGE_MARKER";
export const MINIMIZE_MARKER = "MINIMIZE_MARKER";

//Snackbars
export const OPEN_AUTHENTICATION_SNACKBAR = "OPEN_AUTHENTICATION_SNACKBAR";
export const CLOSE_AUTHENTICATION_SNACKBAR = "CLOSE_AUTHENTICATION_SNACKBAR";
export const OPEN_SIGN_OUT_SNACKBAR = "OPEN_SIGN_OUT_SNACKBAR";
export const CLOSE_SIGN_OUT_SNACKBAR = "OPEN_SIGN_OUT_SNACKBAR";
export const CLOSE_DONE_UPDATE_USER_SNACKBAR = "CLOSE_DONE_UPDATE_USER_SNACKBAR";

//form types
export const OPEN_JOIN_CLEAN_UP_FORM = "OPEN_JOIN_CLEAN_UP_FORM";
export const CLOSE_JOIN_CLEAN_UP_FORM = "CLOSE_JOIN_CLEAN_UP_FORM";
export const OPEN_UPDATE_SITE_FORM = "OPEN_UPDATE_SITE_FORM";
export const CLOSE_UPDATE_SITE_FORM = "CLOSE_UPDATE_SITE_FORM";
export const LOADING_FORM = "LOADING_FORM";
export const STOP_LOADING_FORM = "STOP_LOADING_FORM";

export const DEFAULT_URL = "https://asia-northeast1-rmit-cloud-a2-c8905.cloudfunctions.net/api";
